### PR TITLE
Request size per camera

### PR DESCRIPTION
**Pull request by Bostwickenator**
Set the lib usb request size to the maximum data that the camera returns. This appears to differ between different versions of the camera.

### CODE REVIEW

**Comment by Bostwickenator** [comment]
@alxpettit Hi do you have the Compact Pro of the Compact? I need someone to test this on the Compact as mine died (an unrelated death)

**Comment by alxpettit** [comment]
@Bostwickenator 

I don't think it's a pro. `lsusb` output is simply `289d:0010 Seek Thermal, Inc. PIR206 Thermal Camera [Seek Compact]`.

**Review by alxpettit — COMMENTED** [review]
I don't have the hardware to test this, but it looks fine to me! :)

**Comment by Bostwickenator** [comment]
Oh your patch was merged into the mainline a while back. I'm not sure why it wasn't in this MR. Regardless I'll make sure that sticks this time. I have the Pro and I tested with that if you tested with the regular Compact we have the coverage we need, thanks!!

**Comment by Bostwickenator** [comment]
Just to verify https://github.com/OpenThermal/libseek-thermal/pull/46 the totality of your OpenCV4 fix or did I miss something? I'm compiling against 2 and 3 so I could have missed something specific to 4.

**Comment by alxpettit** [comment]
@Bostwickenator yup that's all it is! :)

**Pull request merged**
